#!/usr/bin/with-contenv bash
DEVICES=$(find /dev/dri /dev/dvb /dev/vchiq /dev/vcsm /dev/vc-mem /dev/video1? -type c -print 2>/dev/null)
echo "GPU Devices: $DEVICES"
for i in ${DEVICES}; do
    # Get the group ID and NAME (if exists) for the current device in the list
    DEVICE_GROUP_ID=$(stat -c '%g' "$i")
    DEVICE_GROUP_NAME=$(getent group "${DEVICE_GROUP_ID}" | awk -F: '{print $1}')

    # If group NAME doesn't exist, create it and assign it the group ID
    if [[ -z "${DEVICE_GROUP_NAME}" ]]; then
        DEVICE_GROUP_NAME="video${RANDOM}"
        groupadd -g "${DEVICE_GROUP_ID}" "${DEVICE_GROUP_NAME}"
    fi
    getent group "${DEVICE_GROUP_NAME}" | grep -q fixmylib || usermod -a -G "${DEVICE_GROUP_NAME}" fixmylib
done
