version: "2"
services:
  fixmylib-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=fixmylib

  fixmylib:
    image: rodrigomideac/fixmylib:latest
    group_add:
      - "109"
      - "989"
    environment:
      - DATABASE_URL=postgresql://postgres:fixmylib@fixmylib-db/postgres
    volumes:
      - ./media-out:/media-out
      - ../media-in:/media-in
    devices:
      - /dev/dri:/dev/dri
