name: fixmylib docker build and push to Docker Hub

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: fixmylib

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker tag
        id: tag
        run: |
          version=$(cargo pkgid | cut -d# -f2 | cut -d: -f2 )
          if [[ "${{ github.ref }}" == "refs/tags/v"* ]]; then
            echo "::set-output name=tag1::latest"
            echo "::set-output name=tag2::$version"
          else
            echo "::set-output name=tag1::${{ github.sha }}"
            echo "::set-output name=tag2::${{ github.sha }}"
          fi

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag1 }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag2 }}
          include-tags: false
          no-include-email: true
